#!/usr/bin/env bash

echo "Stopping Cloudflare Tunnel..."
if [ -f "tunnel.pid" ]; then
    kill $(cat tunnel.pid)
    rm tunnel.pid
    rm tunnel.log
fi

SESSION_NAME="cards"

# Check if the server is already running
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
   echo "killing cards server"
   tmux kill-session -t "$SESSION_NAME" 
else
	echo "no session was found to kill"
fi


echo "System is offline."
